# Generated by Django 4.2.11 on 2024-08-28 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responses',
            old_name='quest',
            new_name='exam',
        ),
    ]
