# Generated by Django 4.2.11 on 2024-09-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0002_rename_quest_responses_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
