# Generated by Django 4.2.11 on 2024-09-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0003_alter_exam_exam_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='semester',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='exam',
            name='shift',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='responses',
            name='attendance_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='responses',
            name='semester',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='responses',
            name='shift',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='responses',
            name='subject',
            field=models.CharField(default='', max_length=200),
        ),
    ]
