# Generated by Django 4.2.11 on 2024-07-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='correct_answers',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
