# Generated by Django 4.2.11 on 2024-07-15 02:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_responses_correct_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
