# Generated by Django 4.2.11 on 2024-07-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quiz_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
