# Generated by Django 4.2.11 on 2024-08-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_quiz_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='submitted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
