# Generated by Django 4.2.11 on 2024-07-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='unique_id',
            new_name='quiz_id',
        ),
    ]
