# Generated by Django 4.2.11 on 2024-09-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_quiz_quiz_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
