# Generated by Django 4.2.11 on 2024-07-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_rename_user_profile_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isLecturer',
            field=models.BooleanField(default=False),
        ),
    ]
