# Generated by Django 4.2.11 on 2024-09-12 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('quest_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('shift', models.CharField(default='', max_length=200)),
                ('semester', models.CharField(default='', max_length=200)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=200)),
                ('submitted_date', models.DateTimeField(blank=True, null=True)),
                ('total_points', models.IntegerField(default=0, null=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dailyquest.quest')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dailyquest.quest')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('output', models.ImageField(default='/quest/outputs/nocode.jpeg', upload_to='quest/outputs/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dailyquest.question')),
            ],
        ),
    ]
