# Generated by Django 4.2.11 on 2024-07-27 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dailyquest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=200)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dailyquest.quest')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('output', models.ImageField(default='/quest/outputs/nocode.jpeg', upload_to='quest/outputs/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dailyquest.question')),
            ],
        ),
    ]
