# Generated by Django 4.2.11 on 2024-09-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dailyquest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='semester',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='responses',
            name='shift',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='responses',
            name='subject',
            field=models.CharField(default='', max_length=200),
        ),
    ]
