# Generated by Django 4.2.11 on 2024-09-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dailyquest', '0002_responses_semester_responses_shift_responses_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='attendance_status',
            field=models.BooleanField(default=False),
        ),
    ]
