# Generated by Django 4.2.11 on 2024-08-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dailyquest', '0003_responses_submitted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='total_points',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
