# Generated by Django 4.2.11 on 2024-09-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dailyquest', '0003_responses_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='quest_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
